device: rpi01

log:
  level: debug

uploadLimit: 50K
downloadLimit: 200K

api:
  port: 8080
  # List of users to add ability of "scopes" without using super admin user
  users:
    - username: big
      password: boss
    - username: admin
      password: $2y$05$iDa0IeAeA2M4y6USukUm2eBeTnWuN24eaGGTsVhT4U6qLElRyqgk.

repositoriesSharedStats:
  billing:
    ovh_xx:
      type: http
      url: https://mockbin.org/bin/f02467dc-7278-4861-9466-30103ca27491
      currency: EUR

repositories:
  global_dd:
    location: /repositories/global
    password: ${REPO_GLOBAL_PWD}
    check:
      schedules:
        - 1d
      priority: inferior
    stats:
      size:
        type: http
        url: https://mockbin.org/bin/06d4e319-2fe5-4633-b99b-1781575c952e
        group: ~
      billing: ovh_xx

backups:
  app1:
    repositories:
      - global_dd
      - name: app1_dd
        location:  /repositories/app1
        password: ${REPO_APP1_PWD}
        check:
          schedules:
            - 6h
            - "*/30 * * * *"
          priority: -32

      - name: app1_ovh
        location: swift:xx:/
        password: abc
        provider:
          name: 'os'
          params:
            auth_url: https://auth.cloud.ovh.net/v3
            project_id: xx
            project_name: "xx"
            region_name: "GRA"
            user_domain_name: "Default"
            project_domain_id: "default"
            username: "user-xx"
            password: "xx"
            identity_api_version: 3
        stats:
          billing: ovh_xx

    paths:
      - /sources
    excludes:
      - .git
      - .sync
      - .truc
    schedules:
      - "*/15 * * * *"
    #watch: true
    watch:
      wait:
        min: 5s
        max: 30s
    priority: superior
    prune:
      schedules:
        - 3m
      priority: inferior
      retentionPolicy:
        nbOfHourly: 24
        nbOfdaily: 7
        nbOfWeekly: 4
        nbOfMonthly: 12
        nbOfYearly: 5
        minTime: 1h
    #- BACKUP_APP1_PRIORITY_IMMEDIATE_AFTER=xxx ?
    #- BACKUP_APP1_STOP_AFTER=xxx ?
    hooks:
      before:
        type: http
        url: https://webhook.site/ce900142-13dc-4eb0-b6e8-3a3393b582ac/dothejob
        timeout: 1m
        retries: 3
        onfailure: continue
        #- BACKUP_APP1_HOOKS_BEFORE_ASYNC= put next of backup process on the queue in case of hook very long ?
        # Add a endpoint trigger to run backup if a service call a http endpoint ?
  app2:
    paths:
      - /test
    repositories:
      - global_dd
      - name: app2_dd
        location: iua
        password: hello
